# Generated by Django 6.0.7 on 2026-08-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(default='Itagüí', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Ej: Especialistas en fades, perfilado de barba...')),
                ('google_maps_link', models.URLField(blank=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='barberia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion.barberia'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.barberia')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('BARBERO', 'Barbero / Dueño')], default='CLIENTE', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestion.barberia')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(to='gestion.servicio'),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
