# Generated by Django 6.0.7 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_cita_sucursal_remove_cita_motivo_cita_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberia',
            name='plan_actual',
            field=models.CharField(choices=[('INDIVIDUAL', 'Plan Individual ($80.000 COP)'), ('STUDIO', 'Plan Studio ($150.000 COP)'), ('ELITE', 'Plan Élite ($200.000 COP)')], default='INDIVIDUAL', max_length=20),
        ),
    ]
